# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 1, 5, 5, 54, 43, 742326, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
